# Generated by Django 3.1.4 on 2021-05-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
