# Generated by Django 3.1.4 on 2021-05-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_wishlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.DecimalField(blank=True, choices=[(0, 'Blue'), (1, 'Green'), (2, 'Black')], decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.DecimalField(blank=True, choices=[(0, 'NEW'), (1, 'USED'), (2, 'COLLECTIBLE'), (3, 'RENEWED')], decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(blank=True, choices=[(0, 'S'), (1, 'M'), (2, 'L'), (3, 'XL'), (4, 'XXL')], decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myWishList', to='product.product'),
        ),
    ]
