# Generated by Django 3.1.4 on 2021-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210526_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.IntegerField(blank=True, choices=[(0, 'Blue'), (1, 'Yellow'), (2, 'Black'), (3, 'Pink'), (3, 'Pink'), (4, 'Grey')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.IntegerField(blank=True, choices=[(0, 'NEW'), (1, 'USED'), (2, 'COLLECTIBLE'), (3, 'RENEWED')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, choices=[(0, 'S'), (1, 'M'), (2, 'L'), (3, 'XL'), (4, 'XXL')], null=True),
        ),
    ]
