# Generated by Django 3.1.4 on 2021-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210526_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.IntegerField(blank=True, choices=[(0, 'Blue'), (1, 'Yellow'), (2, 'Black'), (3, 'Pink'), (4, 'Grey')], null=True),
        ),
    ]
