# Generated by Django 3.1.4 on 2021-05-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210527_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
