# Generated by Django 3.1.4 on 2021-05-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.IntegerField(blank=True, choices=[(0, 'Brown'), (1, 'Yellow'), (2, 'Black'), (3, 'Pink'), (4, 'Grey'), (5, 'Blue')], null=True),
        ),
    ]
